### ISSUE TITLE
New users/members for groups or colectives inside ocp

### ISSUE THREAD

**Issue by XaviP** [FreedomCoop/valuenetwork#125]
We need a method for setup new users/members in groups or colectives inside ocp, that don't use the membership request cycle.

Reproducing a talk in telegram:
E [23.08.16 10:36]
Hello all. We need to setup the requirements for the CVN nodes welcome process in OCP
This would be subgroup of faircoop. Should be 
1. internal group for the CVN working group
2. Membership request group for candidates
and a form, connected with the membership request, in a similar way than freedom coop
The form is here [...] line 114

XaviP, [23.08.16 11:45]
I think it can use the general membership request form or the procedure for colectives to join members (as Cooperative Décentrale has been working on). If we have to develop specific needs and forms for each group or collective which uses ocp, this can be really hard.

E [23.08.16 11:46]
this is not a freedom coop project but faircoop
is not for each group, its a very specific need important for faircoop ecosystem
We need to differenciate one from others, because CVN not needs to be freedom coop members or participants
they would not create projects as CVN

XaviP, [23.08.16 12:39]
Ok, then the CVN working group will be at the same level as a faircoop local node, not a member of freedomcoop.
But the need for groups or collectives to join members can be the same as Cooperative Décentrale or Catalonia faircoop node. So, I think we can find a generic way for groups or colectives that need to join members in ocp but not through freedomcoop membership request form.
I think in this group (Freedom Coop admin) some people has been working about this need, but I don't know which conclusions and aproach to this need they have arrived.

E [23.08.16 13:06]
ok, lets check what other can say about this 😉

Chris Zumbrunn, [23.08.16 13:17]
should it be the joining process to become a member of the collective (or the CVN group in this case) that is handled though an OCP workflow or should it just be the workflow for the OCP account creation after such members have joined the collective (or CVN group) through another process that is handled by this form. That is the question in my opinion. For most collectives, I think it will be just about the OCP account creation for its members. And in the case of the CVN membership is the full membership process, if I understand Enric right.

Chris Zumbrunn, [23.08.16 13:18]
so, maybe it is two different things
whenever it is about membership on not just the OCP account, I guess it would always need a custom form for every collective/group, because I guess the questions asked in the form would be different

Bob Haugen, [23.08.16 14:28]
Here's another big issue:
https://github.com/FreedomCoop/valuenetwork/issues/123

Bob Haugen, [23.08.16 14:30]
[In reply to Chris Zumbrunn]
Custom forms for every group is an interesting problem. Doable, but possibly a lot of UI and back-end design work.
If we want that, I'll look around to see if somebody has already done this as a django plugin.

E [23.08.16 15:02]
faircoop nodes could use same general form that other ocp collectives for participants
But CVN I feel need something specific because is a very key infraestructure that needs be approached with transparence and solvence

bumbum, [23.08.16 15:05]
I think about another 'easy' solution to this recurrent problem (being able to track and moderate a membership process for any group): If we put the 'comments' feature code into a process task as an option, then we can configure a recipe (task template) for the process with the comments thread as the main comunication and data request tool, moderated and managed by project managers (or 'coordinators') of each group. Not necessary a special form (a new table in the db) if we can do this 'coments solution' or we add a whole comunications plugin for django users.

bumbum, [23.08.16 15:06]
so one way can be this special Task with reusable template, and another way is to add a comunication plugin...

**Comment by bhaugen** [comment]
More from Telegram:

[6:15:15 AM] Enric:
The CVN form and process on OCP is quite urgent because the faircoin 2 process is pending of that, and full faircoop is pending of the faircoin 2.
 I think that just the same set of relations between form->candidates->in membership request group, and comments... could be justs copied for CVN.....  isn't it?
 and this could go independent of a general solution about "new users for groups or collectives"
[6:18:16 AM] Bob Haugen:
> Enric
> I think that just the same set of relations between form->candid

Does the CVN form and process need any changes from what exists? (I assume a new form, anyway...)
[6:18:44 AM] Enric:
I agree. Just to make a new form
[6:19:18 AM] Bob Haugen:
Will the new form be filled out like the existing one, by people who are not logged into OCP?
[6:19:33 AM] Enric:
yes
[6:20:01 AM] Bob Haugen:
Will they need to make a faircoin payment, too?
 And will the new members land in the work app or the admin app? Or another way to ask the same question, what kinds of things will they need to do in OCP?
[6:23:08 AM] Enric:
not, they dont need faircoin payment
 just use the comment option for interacting with the admin group
 The accepted CVN would become part of CVN operators group and in the future would be definided how they could use OCP together, but this is not defined for the moment
[6:25:58 AM] Bob Haugen:
So can they land in the work app as a way to get started?
Then most of the flow for Freedom Coop members can be reproduced for the CVN members.
 Mostly just need to define the form.
[6:27:49 AM] Enric:
yes, exactly
[6:28:15 AM] Bob Haugen:
Alternatively, a new app for them, because some of the work app features will not make sense or be used by them.
[6:28:56 AM] Enric:
the form is already drafted in line 114 here: http://board.net/p/CVNOperatorsGuide
 no problem to reproduce the work app, at short term to make it easy, i guess
[6:29:54 AM] Bob Haugen:
> Enric
> the form is already drafted in line 114 here: http://board.net/p

Got it.
> Enric
> no problem to reproduce the work app, at short term to make it e

Somebody should look through the work app features and see if they will be so wrong for the CVNs that we should start a new app.
 If we need to make a lot of  changes in the work app for CVNs, it might be better to start a new app.
 When we get done for now, I'll copy this chat into this github issue:
https://github.com/FreedomCoop/valuenetwork/issues/125
which maybe we should rename again, because it seems to be all about CVNs and not other collectives.

**Comment by bhaugen** [comment]
Here are the components of the Membership Request process. We can probably clone most of these for the CVN request process.
* [MembershipRequest model](https://github.com/FreedomCoop/valuenetwork/blob/master/work/models.py#L13)
* [membership_request template](https://github.com/FreedomCoop/valuenetwork/blob/master/work/templates/work/membership_request.html)
* [MembershipRequestForm](https://github.com/FreedomCoop/valuenetwork/blob/master/work/forms.py#L25)
* [membership_thanks template](https://github.com/FreedomCoop/valuenetwork/blob/master/work/templates/work/membership_thanks.html)
* [membership_request view](https://github.com/FreedomCoop/valuenetwork/blob/master/work/views.py#L1418)
    * this view also creates a task and email notification for Freedom Coop admins
* [membership_request_with_comments template](https://github.com/FreedomCoop/valuenetwork/blob/master/work/templates/work/membership_request_with_comments.html)
* [membership_discussion view, which presents the membership_request_with_comments template](https://github.com/FreedomCoop/valuenetwork/blob/master/work/views.py#L1526)
* [membership_requests template in Admin app](https://github.com/FreedomCoop/valuenetwork/blob/master/valuenetwork/templates/valueaccounting/membership_requests.html)
    * we have a request to add decline and delete functions to that page
* [membership_requests view in Admin app](https://github.com/FreedomCoop/valuenetwork/blob/master/valuenetwork/valueaccounting/views.py)
* [single membership_request template in Admin app](https://github.com/FreedomCoop/valuenetwork/blob/master/valuenetwork/templates/valueaccounting/membership_request.html)
* [membership_request view in Admin app](https://github.com/FreedomCoop/valuenetwork/blob/master/valuenetwork/valueaccounting/views.py#L13221)
    * this view includes a form to create an agent from the membership request info

By the way, any new view also requires an urlpattern in either work/urls.py or valueaccounting/urls.py, depending on which app the view is in.

**Comment by bhaugen** [comment]
There's one other part of the membership request process, which is that the member's discussion page is linked to their listing on the organization and all agents pages. We could link it to other places as well, or just figure out one best place to put the link. But otherwise, the coop admins don't know how to get to the membership discussion page.

**Comment by XaviP** [comment]
Sorry, I think that CVN admins can follow the candidate process by a mailling list, telegram, FairNetwork or whatever, and when a candidate is approved, the group admin can setup this user for using ocp as a task manager.
I think we have many work that is of prioritary.
But maybe we can study how an admin group can setup a new user in his/her group.

**Comment by XaviP** [comment]
Duplicate: https://github.com/FreedomCoop/valuenetwork/issues/90
Closing. Please reopen if you need it.
