### ISSUE TITLE
How to translate DB strings?

### ISSUE THREAD

**Issue by bum2** [FreedomCoop/valuenetwork#145]
We need a system for translating some strings recorded in the db (not hardcoded), like the ones for the help system, the description of agents, the custom questions in any project forms, etc.
Let's find a good way to translate them,  when they're retrieved from the db and before showing up, depending on the UI language. I supose we will not use .po files or transifex service to help on this, but i think is good to keep db strings as such (not elsewhere) and because they can change more often and can be private.

**Comment by bhaugen** [comment]
https://djangopackages.org/grids/g/model-translation/

I have no experience or knowledge about any of them.

**Comment by bhaugen** [comment]
Preliminary results of research into Django model-translation packages:

3 packages stand out, listed with links to their documentation:
*  django-modeltranslation: https://django-modeltranslation.readthedocs.org/en/latest
*  django-hvad: http://django-hvad.readthedocs.org/
*  django-parler: https://django-parler.readthedocs.io/

One big difference is that hvad and parler add extra models and db tables (I'm not sure yet whether this means one table for all languages, or one table for each language), while modeltranslation adds extra fields to the same table for each language.

Here is a comparison from django-parler: https://django-parler.readthedocs.io/en/latest/background.html

Another comparison, mostly interesting because of the details on django-modeltranslation: http://blog.muhuk.com/2010/01/06/dynamic-translation-apps-for-django.html

Article featuring django-hvad: http://www.ubiwhere.com/en/news/2015/03/05/using-django-rest-framework-model-translations/

It's clear from those comparison articles that model translation is complex and can have a lot of pitfalls. I don't think we will be able to choose well without experimenting with more than one package.

Next steps: experiment first with django-parler to understand the separate-table approach.

**Comment by capiscuas** [comment]
Hi, I don't understand what DB strings are you refering. 
I see in the code you are already using the default Django translation _("translate-me") capabilities.

https://docs.djangoproject.com/es/1.10/topics/i18n/translation/

can you give me an example?
Thanks

**Comment by bhaugen** [comment]
@bum2 's original post above included some examples. One example is we are using [fobi forms](https://github.com/barseghyanartur/django-fobi) which are user-defined with all of the form contents in the database. Does not fit the default Django translation pattern, but Django packages includes several plugins that will translate database fields.

**Comment by carbans** [comment]
I'm working on this issue.

**Comment by bum2** [comment]
Marvelous @carbans !!
The existent db texts that needs to be translatable now are:
- Name or value field of exchange types, resource types, facets, facetvalues, etc
- Name and description of projects or any context agent
- Custom form fields labels for moderated projects (fobi system)
- Help system

I think we need to set a list of table.fields that need translation, so we can put any field to the list and translate whatever is needed. The first version can have simply an 'admin side' way of translating that strings, but for a second version we'll need to make the GUI flow for project coordinators to translate their project strings (basically name and description) or custom fields and types, without any admin work.

**Comment by XaviP** [comment]
Here some comparation between model transation third packages:
https://www.elements.nl/2017/04/20/djangocon-2017-in-florence/
![blog_djangocon_data_internationalization_03-768x484](https://cloud.githubusercontent.com/assets/6750293/25522214/63ec4b84-2c02-11e7-8b2f-97d6fd9b5b14.png)

I've been playing around `django-hvad` and it works well, but it's not easy to implement as the models and the queries must be modificated:

- in models, you need to separate translatable fields:

```
class MyModel(TranslatableModel):
    translations = TranslatedFields(
      slug = models.SlugField(unique=True, verbose_name=_("Path")),
      name = models.CharField(max_length=255, verbose_name=_("Name")),
      text = models.TextField(verbose_name=_("Description")),
    )
    created = models.DateTimeField(auto_now_add=True, editable=False, verbose_name=_("Created"))
    last_updated = models.DateTimeField(auto_now=True, editable=False, verbose_name=_("Last updated"))
```

- in queries, you need to define the language in between, but most filters works ok. For example:

```
objects_list = MyModel.objects.language().all()
```

It works in django 1.11, and I think it's really good maintained.
In case we want to use it, we can make some testing with one or two models and see if it cover our needs, and doesn't require much work.

**Comment by bum2** [comment]
I've been trying with modeltranslation and I think it works best, no new models or ids around...
One Agent = one UID, one Resource = one UID, etc

The only tricky part about it is at the migration moment when the translatable fields are Unique, because the new model fields added for every lang in the same model (say name_en, name_es, etc) have the same characteristics of the original field (unique, etc) and after creation of the new fields they became empty, and that gives error on render because of the uniqueness.
Some useful scripts of the modeltranslation system are used to deal with this and fill up the new fields with the data in the original field. The overall process is explained at https://github.com/FreedomCoop/valuenetwork/blob/master/docs/translations.md 

Now is deployed into production, so let's see how it behaves in the long run.
