### ISSUE TITLE
Upgrading from django 1.8 to 1.11

### ISSUE THREAD

**Issue by XaviP** [FreedomCoop/valuenetwork#214]
- Official django release notes: [1.9](https://docs.djangoproject.com/en/1.9/releases/1.9/), [1.10](https://docs.djangoproject.com/en/1.10/releases/1.10/), [1.11](https://docs.djangoproject.com/en/1.11/releases/1.11/)
- We need to write an open workflow for other forks (or think how to share the update, merge possible?)

**Comment by bhaugen** [comment]
People (including you) are talking about refactoring and modularization so that we can all share all the modules we want to use, which could mean no or very few forks. Don't know where that would fit in the roadmap and priorities, but that would take us all into the future in a much better spaceship.
