### ISSUE TITLE
Simplify calls to electrum-wallet to one per request

### ISSUE THREAD

**Issue by XaviP** [FreedomCoop/valuenetwork#297]
There's a timeout when calling to the electrum-wallet, in case of failure of daemon, network or no response from the server. It's needed to simplify to one call per request in order to work propertly.
In work/faircoin_account and work/faircoin_history templates, the wallet is called many times. I think it's possible to call only one time and put the values in a variable, to use along the template. This can alleviate the wallet work, and make the timeout work.

**Comment by bum2** [comment]
I'm looking into this issue, trying to find out a way to minimize the calls... but i don't know how to test properly: if i try to stop the daemon in testocp it remains running (or starts again immediately, because it says 'daemon stopped' but status gives always 'running') ...
Maybe is interesting to have one way to check the daemon_is_up without calling the nrp send_command (which has the timeout). It can work the approach in the first answer at http://stackoverflow.com/questions/26123137/python-daemon-checking-to-have-one-daemon-run-at-all-times?rq=1 checking for a lockfile, using the phyton-daemon library... other approaches i see are about finding the pid or a grep on the system processes... but i didn't try any of those solutions. If you think is interesting, perhaps someone can focus on this?
I'm trying some changes to minimize daemon calls from templates in a new `less-wallet-calls` branch (please help if you can)... I know is not enough to check if the daemon is up, we need to check the network server mainly, asynchronously. Perhaps this is useful http://stackoverflow.com/questions/9110593/asynchronous-requests-with-python-requests ... if we can make it really asynchronously (ajax style) we don't need to rely on the timeout system.
I keep on trying to reduce the calls, but there are many anyway: daemon_is_up, is_connected, get_address_balance, network_fee, etc...

**Comment by XaviP** [comment]
- To test, I think it's simpler than you explain: if you run ocp in local without wallet, you we'll see the number of callings in the shell (as debug prints)
- In ocp, new addresses demand and transaction broadcast are completly asyncronous. The actions are done from a new process which cron starts. 
- One possibility to reduce the calls is delete object wallet methods from templates, and create a new variable in views with only one call (and create if necessary a new method which gets all information) In faircoin_account.html only is needed balance and not confirmed balance, which is a simple call to the wallet. In faircoin_history.html, only is needed a call to the address history.

**Comment by XaviP** [comment]
I think you missed push the new branch, I don't see less-wallet-call branch in github.

**Comment by XaviP** [comment]
The profile page also make calls to wallet and must be deleted.

**Comment by bum2** [comment]
Oups, yes i forgot to push the branch sorry... now is here, but as a work-in-progress to try an approach... feel free to continue with this branch (perhaps focusing more the wallet vars and checks in the 'ExchangeService' part?)... 
I need to create another branch for "custom-shares" developments and will focus on that in the next days...
By the way, meanwhile, will be marvelous to merge the 'skills-profile' branch in master and put in prod (if that occurs i need to setup some configs in prod for it to work good, basically to map prod skills with the skills tree)...

**Comment by XaviP** [comment]
> and checks in the 'ExchangeService' part
I don't know how can be removed calls from ExchangeService, I think all are necessary:
- when creating a transaction, it needs to know the fee value:
https://github.com/FreedomCoop/valuenetwork/blob/master/valuenetwork/valueaccounting/service.py#L130
- when visiting history page, it needs to check if all transactions in blockchain are inside ocp:
https://github.com/FreedomCoop/valuenetwork/blob/master/valuenetwork/valueaccounting/service.py#L205
- if there's any transaction in blockchain that is not in ocp, it needs transaction information:
https://github.com/FreedomCoop/valuenetwork/blob/master/valuenetwork/valueaccounting/service.py#L217

I reviewed some of what you push in less-wallet-calls branch, but I think it's missing to remove all calls to is_mine(), checking that is only necessary for developers, but it's calling in production too !!

**Comment by XaviP** [comment]
> By the way, meanwhile, will be marvelous to merge the 'skills-profile' branch in master and put in prod

Please, do it yourself !

**Comment by XaviP** [comment]
Using requests lib in electrum_fair_nrp.py (see https://github.com/FreedomCoop/valuenetwork/commit/3ed559175a528a2f4c755b84e1ef8a9e82f60c11), errors and timeout control is better supported now from this module. So, no need to control daemon_is_up() or is_connected() in faircoin_utils.py. This will reduce significantly the daemon calls. I'm on it.

**Comment by XaviP** [comment]
Achieved a reasonable low number of calls per request. Closing.
