### ISSUE TITLE
Why every internal faircoin transaction has two events related??

### ISSUE THREAD

**Issue by XaviP** [FreedomCoop/valuenetwork#321]
All info needed in an internal faircoin transaction is stored in one event, but the system is storing two events with the same info. It doesn't seem very optimized to me.

**Comment by XaviP** [comment]
Ok, I understand it now. It's because the fee, right?

**Comment by fosterlynn** [comment]
@XaviP I haven't looked the faircoin transactions specifically, but here is how the transfers are structured (there is history there, this is a rewrite of the original structure which had one transfer event, and ValueFlows has changed it again).

There are 2 EconomicEvents for each Transfer, a Give event and a Receive event.  That is because then an event affects only one resource (fc address in this case), which is the general model.  So fc is decremented from the giving resource, and incremented on the receiving resource.  It also accommodates when one agent in the transfer is not in the network - then you would have only the Give or only the Receive, as the other side of the transfer is not in your system.  Theoretically the outside agent would have the other side of the transfer recorded, and they could be matched up in the ether if needed.

The fee is something else, I don't know how it was implemented, but according to this model, it would also have 2 events (one transfer), the fee coming from one agent/resoruce and going to another agent/resource.

**Comment by bhaugen** [comment]
> The fee is something else, I don't know how it was implemented, but according to this model, it would also have 2 events (one transfer), the fee coming from one agent/resoruce and going to another agent/resource.

The fee has not been implemented as a separate economic event. It is subtracted from the Give quantity, so that the Receive quantity may be different (less than) the Give. In other words, the effect of the transfer will be different for each faircoin address: more will be decreased from the Give address than is added to the Receive address.

**Comment by XaviP** [comment]
Thank you very much for the explanations !!
