### ISSUE TITLE
[faircoin2] New fee calculation

### ISSUE THREAD

**Issue by XaviP** [FreedomCoop/valuenetwork#326]
Since now, all transactions in ocp where using a fixed fee (0,001 FAIR) This was giving errors in transactions larger than 1KB (more than 7-8 inputs+outputs) that were solved manually, increasing the fee.
Now, electrumfair (faircoin2) has a fee estimation when the transaction is done (based in a fee rate of 0,01 FAIR per KB) The wallet calcules the fee when it knows how large it is.

So, as the EconomicEvents are saved before to know how large is the transaction, some changes in code are needed:
- Save the EconomicEvent without any fee.
- When the cron makes the transaction, add to the amount of the giving event the resulting fee.
- In the send transaction form, when calculating the limit to spend, it must use a estimated big fee (0,02??), to avoid NotEnoughtFounds errors in transactions.  

This issue is connected with a feature request that was waiting in the queue (https://github.com/FreedomCoop/valuenetwork/issues/253) and a recent bug (https://github.com/FreedomCoop/valuenetwork/issues/325)

**Comment by XaviP** [comment]
Changes in branch new_fee_calculation:
- Events are saved without fee
https://github.com/FreedomCoop/valuenetwork/blob/new_fee_calculation/valuenetwork/valueaccounting/service.py#L198
- Daemon returns fee in make_transaction_from_address once the tx is mounted:
https://github.com/FreedomCoop/valuenetwork/blob/new_fee_calculation/faircoin/daemon/daemon.py.sample#L145
- process_faircoin_requests add the fee to event.quantity:
https://github.com/FreedomCoop/valuenetwork/blob/new_fee_calculation/faircoin/process_faircoin_requests.py#L180

@bhaugen @fosterlynn In process_faircoin_requests I'm adding the fee to the "Give" event:
```
if event.event_type.name=="Give":
    qty = event.quantity
    qty += Decimal(fee) / Decimal("1.e6")
    event.quantity = qty
    event.save()
```

I don't know how to do it when the event type is "Distribution". Same way? How you would do it?

**Comment by fosterlynn** [comment]
>In process_faircoin_requests I'm adding the fee to the "Give" event:

From talking to @bhaugen it sounds like that is how it was done before, and the Receive event for the fee is outside of the OCP boundaries, so that seems right.

>I don't know how to do it when the event type is "Distribution". Same way? How you would do it?

I am assuming there will be a fee whenever faircoin is transferred, so that would include distributions then.  Basically faircoin that will be distributed comes into the system to usually a project or other context agent.  Will the context agents have extra faircoin to pay fees to distribute income?  Or should the fee be subtracted from what gets distributed, so a little less gets divided up among the distribution recipients?  Or should each recipient of a distribution pay their fee?  I tend to think it should be one of the latter options, because it may often happen that a context agent has no other income from which to pay fees.  

I think the easiest then would be to subtract it from each receive event.  So then a context agent is giving the whole thing, but by the time it is received, it has paid its fee. 

Note, when we re-wrote exchanges to include Transfers with Give and Receive events, we didn't re-write the distributions, even though they are conceptually Transfers also.  The event types on a distribution are Cash Disbursement and Distribution.  So the Cash Disbursement event would be the whole amount, the Distribution event would have the fee subtracted.  (Don't be confused that there is an event type of Distribution and also a class Distribution, here we are talking about events.)

Does this make sense @XaviP @bhaugen ?

**Comment by XaviP** [comment]
> it sounds like that is how it was done before, and the Receive event for the fee is outside of the OCP boundaries, so that seems right.

Well, until now, we were substracting fee from the receiver. Now I'm changing the behaviour because of this feature request that was waiting in the queue:
https://github.com/FreedomCoop/valuenetwork/issues/253
So, now the sender will be the fee payer, and the exact amount written in the form will arrive to the payed agent.

The usual behaviour in all wallets is that fees are charged to the payer. So, does it works like this in a distribution too?? The agent how pays is the one who charge the fees in all transactions??

**Comment by fosterlynn** [comment]
>The usual behaviour in all wallets is that fees are charged to the payer. So, does it works like this in a distribution too?? The agent who pays is the one who is been charged with the fees in all transactions and the agents receive the exact amount??

Yes of course it is really a policy decision, like all of these fee questions.  And it hasn't happened yet, because no previous uses of NRP involved crypto-currencies and therefore a fee for transferring money. We could ask the group, but I don't think people are thinking about distribution yet.

Distributions are a bit different, because it is a question if there is any income other than that to be distributed, in many of these projects.  The payer is not really different than the people who will be payed in a distribution, the payer is just managing the distribution of income for work done collectively.  But if you want it to be consistent, which certainly has some advantages, I suppose groups can figure that out themselves if they need to, and maybe collect and keep a reserve for fees.  Or just always distribute a little less than the income received to be safe.
