### ISSUE TITLE
How should work be validated for value distributions?

### ISSUE THREAD

**Issue by bhaugen** [FreedomCoop/valuenetwork#390]
1.What should be validated? What level of granularity?
* All work done by a person of a type of work for a month?
* Project?
** Total work done by a person on a project?
*** Process?
***** Total work done by a person on a process?
***** Including unplanned as well as planned work?
******* Work requirement?
******** Total work done by a person on a work requirement?
* Some other criteria?

2. Where should it be validated?
** Which app?
*** In OCP?
*** In Kispagi?
*** Separate validation app?

3. Detailed design of validation

Anything else we should think about and discuss about validation?

**Comment by capiscuas** [comment]
1. I think validation should be done in the process level, just with 2 agents(that hasn't logged any work event yet) validating the task with some comment(in the future we can set a label or worktypes).

2. I think validation should be inside the task manager(OCP, etc), so that we don't have to create more users+groups+permissions duplication, and it can be shown in the kanban of the task manager for example(if we use labels in the future.)

**Comment by MichalisKas** [comment]
1. To be honest the only thing that can be validated in such a decentralized and open work space like OCW is probably the outcome of each work plan. We need to have something concrete to validate, as I see it unlikely to be able to judge someone's work hours, generally speaking.
In that sense I would say that we should be able to validate each specific 'work requirement' (planned or unplanned), specifically the outcome produced, but not each participant's hours of work in there. In case that 2+ people collaborated in that outcome, they should be all be responsible of the work hours logged and reply if someone questions that.

Another option, that is probably needed, has to do with repeated/monthly work, usually done by people with fixed income. There we could still have the option to validate each 'work requirement' but would be also useful if we could validate the whole monthly process at once also.

2. Since I see this from the user perspective, participants of the OCW that log their work are the same that will then go on and validate other people's work. So these actions should be easy to do inside the same platform. Don't know which tool is better for doing so, but should be inter-connected to OCP imo.

3. I can just add some features I have in mind...
- Validators (agents) should be shown in the Process somewhere.
- These 2-step validation function should be easy to do, possibly through just a button.
- Each validator must have the ability to undo its validation, for unfinished processes.
- A second validation would make the Process move automatically from Done to Validated in the kanban view.

**Comment by fosterlynn** [comment]
>To be honest the only thing that can be validated in such a decentralized and open work space like OCW is probably the outcome of each work plan. We need to have something concrete to validate, as I see it unlikely to be able to judge someone's work hours, generally speaking.

In OCP, this could be the deliverable(s) from each plan perhaps.  (That is an output event/resource, as opposed to work input events.)

This is pretty clean when it is ongoing work that is planned and validated by month.  It is also pretty clean when the plan is completed within a month.

When a plan spans months, then perhaps some kind of monthly validation would work?

**Comment by MichalisKas** [comment]
1. To be honest the only thing that can be validated in such a decentralized and open work space like OCW is probably the outcome of each work plan. We need to have something concrete to validate, as I see it unlikely to be able to judge someone's work hours, generally speaking.
In that sense I would say that we should be able to validate each specific 'work requirement' (planned or unplanned), specifically the outcome produced, but not each participant's hours of work in there. In case that 2+ people collaborated in that outcome, they should be all be responsible of the work hours logged and reply if someone questions that.

Another option, that is probably needed, has to do with repeated/monthly work, usually done by people with fixed income. There we could still have the option to validate each 'work requirement' but would be also useful if we could validate the whole monthly process at once also.

2. Since I see this from the user perspective, participants of the OCW that log their work are the same that will then go on and validate other people's work. So these actions should be easy to do inside the same platform. Don't know which tool is better for doing so, but should be inter-connected to OCP imo.

3. I can just add some features I have in mind...
- Validators (agents) should be shown in the Process somewhere.
- These 2-step validation function should be easy to do, possibly through just a button.
- Each validator must have the ability to undo its validation, for unfinished processes.
- A second validation would make the Process move automatically from Done to Validated in the kanban view.

**Comment by MichalisKas** [comment]
The problem with validating either the whole process or the deliverable(s) is that these could take more than a month to produce. Think of a campaign, for example, that is going on for several months. There we would need to validate specific work people did for each month, like writing an article, posting in social media, communicating and facilitating the campaign etc

**Comment by capiscuas** [comment]
I think the granularity of a process should be as small as possible: a process can be writing an article, posting in social media, etc...  things that can be finished within a month for sure and can be validated by people that has not logged hours in that process(otherwise the validation will be biased).

**Comment by fosterlynn** [comment]
>I think the granularity of a process should be as small as possible: a process can be writing an article, posting in social media, etc... things that can be finished within a month for sure and can be validated by people that has not logged hours in that process(otherwise the validation will be biased).

Actually in OCP, processes should be as big or small as needed. That decision has more to do with creating outputs/outcomes, and dependencies with other processes (also governed by resource flows). Other groups have used large processes quite successfully when the final deliverable is large. You can break the work down inside the process to smaller chunks as needed (with commitments/requiremetns), or those can be large too if it makes sense. In the case of OCW, there are pretty much small processes by its nature.  

But still even small processes could cross over 2 months.

So I think that if OCW wants to pay monthly, we need software that works for that even if processes cross month boundaries.  Processes and months are driven by completely separate logic. :)

**Comment by fosterlynn** [comment]
Another possible issue with validating at the process level: what if several people worked on something but people think that one of those people was slacking off or logging work dishonestly?  The work got done and so the deliverable can be validated, but...... ?

**Comment by MichalisKas** [comment]
> Another possible issue with validating at the process level: what if several people worked on something but people think that one of those people was slacking off or logging work dishonestly? The work got done and so the deliverable can be validated, but...... ?

I think this stands even if we decide to validate a work event where 2+ agents participated.
I've given some thought on that and I think that the main ones that can fairly judge this are the people that collaborated in that process. That contradicts with the need to have validators different than the ones who did the actual work, but I believe we should keep like this. So maybe in such case, someone from the people which collaborated should raise an issue if thinks something is made in a dishonest way.

**Comment by fosterlynn** [comment]
>I think this stands even if we decide to validate a work event where 2+ agents participated.

Just to clarify: a work event involves only one person.  A work requirement can involve many people logging work events against the requirement.  Work events tend to be by date, so you can get a lot of them sometimes, so that would be a lot of validation.  (This isn't an opinion about how you should do it, just to clarify the structure. :)  )

**Comment by capiscuas** [comment]
in Kispagi validation is already being detected inside the testocp workevents in a process level, thks to Bob&Lynn now i know how to access the commitments and their workevents inside, therefore we can apply validation in commitment scale, not process.

**Comment by TiberiusB** [comment]
Hi all,

Interesting discussion... *I want to contribute more to this, please point
me to other related questions*.

I did not read the entire thread... no time but I hope my input will be
valuable.

*From Sensorica experience*:

First, I want to direct you to the page on Contributions on the OVN wiki.
There is a lot of info there...
http://valuenetwork.referata.com/wiki/Contributions

We consider* a log* as a claim for a *contribution
<http://valuenetwork.referata.com/wiki/Contributions>*. This idea was
introduced by Kurt a long time ago.

Only *contributions* are taken into consideration for *benefit
redistribution
<http://valuenetwork.referata.com/w/index.php?title=Access_to_benefits_algorithm&redirect=no>*
.

I think validation should be performed at the process level. That is
because validation needs to be done by people close to the activity, and
not too far in time from where the activity has been logged (people
forget!). In fact, SENSORICA uses a clause in Project Governance: logging
after some time of execution is penalized (see Project Governance template
<https://docs.google.com/document/d/16bgsksdkAf3aSEK1x6LLm4iXh-bmyGPH2zQRVqUDONk/edit#heading=h.sxujqwe6affv>,
and you'll find in there an incident where someone did a lump log for a
month and that caused social problems).

For *process* logging.
In Sensorica, if someone raises a red flag for a log we have a discussion
and adjust it. In the Sensorica NRP can can't flag logs. So this happens
informally. We had very few cases in the past of invalidating or modifying
someone's logs, in small settings people nurture their reputation. I expect
the situation to change at large scale, people will try to cheat, so we
need to be able to flag logs.

Logs can only be validated in proximity: only people that operate in the
same context have the knowledge to validate a log. *I advise against active
validation of logs*. From my 8 years of experience with Sensorica, people
don't like that overhead, and you'll have people screaming around to other
people to validate their logs. Some have proposed to making the act of
validating logs a contribution.

I prefer to tie validation to the signaling system
<http://valuenetwork.referata.com/w/index.php?title=Signaling_system&action=edit>.
For example, new affiliates to a project can be placed automatically in the
list of notifications of those who contribute to the same processes and
projects, to be peer reviewed. Or anyone in the project can set up the
notification system to patrol projects, (types of) processes, affiliates,
types of work, ...
In a process, I also prefer to have the act of marking a process as
*Finished* notify all contributors to peer review. If no one raises a red
flag for a set *delay*, all logs become contributions.

Not all logs are done in a process, because some activities are open
(administration, communication, ...).  See "*non-production work"*.
Not all logs are tied to deliverables. See "*non-production work"*.
In these cases, I prefer the same signaling / notification system to be
used in patrolling logs by process, by affiliate, or project, or type of
work, with higher priority or an automated setting for new affiliates, or
affiliates with low reputation scores.

*How to avoid collusion? *
What if a small group of people validate each others? I think at some point
deliverables need to be taken into consideration, if the activity creates
deliverables.
We haven't done much AI thinking for the NRP, but I think it is not
difficult to create a system that compares processes and triggers alarms /
suggestions to check this or that.

**Comment by TiberiusB** [comment]
In the link to the OVN wiki to the page "Contribution" you'll find other
forms of contributions: financial, material, ...
These are modeled as Exchange type in the NRP. But they all behave
differently and validation is specific to every one of those.

Going beyond contributions, other things need to be validated. For example,
a process produces a Resource. This resource can be a design (a file), an
report, a publication, a prototype, a product, ... This event will affect
the Inventory. How do we know that the file with the proper content has
been created and someone hasen't uploaded just a junk file?  How do we know
that a prototype, a physical thing has been created and placed in some
location.  Moreover, when we think about creation we also need to think
about use and about recycling or distrustion.   We should also think about
displacement : how do we know that a 3D printer has been moved from one lab
to another?
