### ISSUE TITLE
Roles and Permissions system

### ISSUE THREAD

**Issue by bum2** [FreedomCoop/valuenetwork#71]
The combination of groups of users (roles) with a set of permissions each group, i don't know if is well resolved in ocp (the typical way is just combine permissions with user-groups, to avoid boolean fields in the profiles). 
If is not easy to use this structure, then maybe a script in cron can do the trick, putting selected permissions to individual users grouped into ocp somewhat or grouped into django admin backend. Roles details are on the launch pad.
Depending on the roles, is needed to filter whole pages, menu items, types or options around, or even sections of a page or simply buttons or strings.
Now is only filtered the menus by roles ('worker' and 'admin'), but the pages and the permissions remain the same (you just need to know or guess the right urls, and became an admin youself)...

**Comment by bhaugen** [comment]
@bum2 - are you thinking of something like [Django group permissions](
https://docs.djangoproject.com/en/1.8/topics/auth/default/#permissions-and-authorization)?

Those only work in Django admin, and they only deal with CRUD (create, read, update and delete) actions on model instances. We could use them in the rest of the system, too, but we're also talking about access: who can see what, and actions: who can do what, in a lot of other ways besides CRUD.

And that adds one more organizational element to the system.

We already have a rich organizational structure that could be used for permissions. See https://testocp.freedomcoop.eu/accounting/projects/ and https://testocp.freedomcoop.eu/accounting/radial-graph/7/ , for example.

Here's you: https://testocp.freedomcoop.eu/accounting/agent/56/

You are now a member of Freedom Coop, Catalonia Node, and Membership Requests. Maybe you should be able to see everything in those organizations.

Freedom Coop has a number of children: Call Center Coop Network, Membership Requests, Pilot Admin Team, Tech team, and Spanish Accounting & Legal Team. Since you are a member of Freedom Coop, should you also be able to see everything in the child organizations? Or maybe only if you had some other relationship to Freedom Coop, not just Member. Maybe Admin?

Membership probably doesn't give you too many permissions. But what if you were a manager of a project? That would give you more permissions, but only for that project.

What do you think? We can add as many types of associations between Agents as we want, and use them for access and action permissions.

**Comment by bhaugen** [comment]
I just added a Project Manager association. So now the Pilot Admin Team has a manager:
https://testocp.freedomcoop.eu/accounting/agent/31/

As I wrote in Telegram, this is one example of why I think the organizational structure defines Roles and is important for Permissions. Another example is E's comment that a coop worker should only see projects that they belong to.

**Comment by bhaugen** [comment]
@bum2 - do you really want to work on this issue? As a programmer? In Django? If so, that would be great!

**Comment by bum2** [comment]
The projects can be of three kinds: 
- Open (any user can pick tasks and became participant)
- public but Moderated (acceptance of new participants is moderated by project managers, can have public tasks or only-staff tasks)
- Private (no public tasks, not listed project)
The read permission on projects will depend on this 'kinds'.
The edit permission will depend on being manager or not.
Dear @bhaugen, i'm not sure about how to start (please help!) but i imagine will be needed to apply the permission filters at the page template level, or in a similar way of the 'login_required' solved issue. If you can advance in this issue, i can focus in many other pending things (not only code issues). If not, asap i can try to work on this at code level.

**Comment by bhaugen** [comment]
> The projects can be of three kinds:

> Open (any user can pick tasks and became participant)
public but Moderated (acceptance of new participants is moderated by project managers, can have public tasks or only-staff tasks)
Private (no public tasks, not listed project)

That means we will need either some new fields on projects, or when creating a project, different types (that's Agent Type on the Create New Agent form).

**Comment by bhaugen** [comment]
> i'm not sure about how to start (please help!) but i imagine will be needed to apply the permission filters at the page template level, or in a similar way of the 'login_required' solved issue.

The login_required solution was pretty easy: do it once for all pages, and allow exceptions only for pages that do not require login.

Permissions will be a lot more complicated. Might be difficult for somebody who has not worked in this code base before.

**Comment by bum2** [comment]
You are true, is better if you can design the solution. After that we can tune together the fine grain permissions, but with a clear system to do it (at configuration level or at code level, you choose)

**Comment by bhaugen** [comment]
It will need to be a combination of configuration and code. Unfortunately.

**Comment by bhaugen** [comment]
Proposal: https://github.com/FreedomCoop/valuenetwork/issues/80

**Comment by bhaugen** [comment]
I just pushed the first experiment combining permissions and tasks. Does not totally satisfy this issue or #65 but it's a start.

It does not yet deal with permissions for project managers, but it does limit the selections of context agents (projects) to those the use is associated with.

See also question on #65

**Comment by bum2** [comment]
Great @bhaugen !
All this filtering of things is very good to do it, but there's something even more prioritarian: the permissons on page access. 
If you are logged as a regular user, and if you know or guess the url of some admin page, nothing prevents you to go and edit all sort of things (access in pages is open for any logged user). The parts only for members or only for admins must be non-accessible if you are a participant or candidate (only menu buttons hiding is not enough).

**Comment by bhaugen** [comment]
Yup. Needs to be done. I wonder if the login_required middleware could do it...hmmm...

**Comment by bhaugen** [comment]
What's left to do on this issue?

**Comment by XaviP** [comment]
Solved. Please, reopen if needed.
