### ISSUE TITLE
Wording changes

### ISSUE THREAD

**Issue by skoria** [FreedomCoop/valuenetwork#76]
Here are some changes for some terms in ocp:

    Todo -> Task (for simple tasks people can add in the worker app)
    
     "recipe" -> "task template"

    change recipe -> "change task template"

    exchange -> request

    "add usable" -> "add resource use"

    "non-process logged" -> "other tasks"

    "process logging" -> "main tasks"

**Comment by bhaugen** [comment]
I'll make the Todo -> Task change. It's clear and not a problem.

But how should I deal with word changes where I think the new name shows that people don't understand how the OCP system works well enough yet? Just make the change anyway and let it get resolved later? Or should we discuss more?

For example, the difference between non-process and process logging is not new vs current work. Once people understand what is going on, those names will be confusing.

Likewise "add usable" might be a poor word choice, but it means the process will use a resource rather than consuming it. Using a resource means that resource still exists after you use it (like a computer). Consuming a resource means it is gone after you consume it (like lunch). So "add resource" doesn't tell you what will happen to the resource.

**Comment by skoria** [comment]
CHanges are being discussed on the main pad and we'll update when done..

**Comment by bhaugen** [comment]
This would also be a great easy job for a programmer who is new to the OCP code. And in general, it's your fork, make whatever wording changes you want. I'm just commenting.

**Comment by bum2** [comment]
I will try to assume the issue if i find the time. The current wording status is now:

- Recipe -> "Task Template"
- change recipe -> "change task template"
 
- Exchange -> "Movement"
 
- Add usable -> "Add reusable resource"
 
- Process logging" -> "log main tasks" (other tries: "Main tasks for me", "my main tasks"
- Non-process logging -> "log other tasks" (other tries: "Other tasks i did", "Record other finished tasks", "Log other done tasks")

**Comment by XaviP** [comment]
Solved. Please, reopen if needed.
